name             'cheftest'
maintainer       'YOUR_NAME'
maintainer_email 'YOUR_EMAIL'
license          'All rights reserved'
description      'Installs/Configures cheftest'
long_description 'Installs/Configures cheftest'
version          '0.1.0'

depends 'apache2'
depends 'mysql'
depends 'php'