name             'lampchef'
maintainer       'Shout It Louder'
maintainer_email 'YOUR_EMAIL'
license          'All rights reserved'
description      'Installs/Configures lampchef'
long_description 'Installs/Configures lampchef'
version          '1.2.0'

depends 'apache2'
depends 'mysql'
depends 'php'
depends 'composer'
depends 'git'
depends 'sudo'
depends 'ssh_known_hosts'
depends 'user'